### ISSUE TITLE
Add keyring support

### ISSUE THREAD

**Issue by marcopaganini** [marcopaganini/termotp#3]
Add keyring support, so that passwords can be cached on the keyring. Use some abstraction layer like [go-keyring](https://github.com/zalando/go-keyring) or [keyring](https://github.com/99designs/keyring) so this will work on different platforms.

**Comment by sam-artuso** [comment]
is this gonna happen any time soon?

**Comment by marcopaganini** [comment]
Yeah I like the idea and it should happen as soon as I can get a few
minutes to work on it.

**Comment by marcopaganini** [comment]
@sam-artuso Version double-Oh-seven (0.0.7) is ready with keyring support. Could you give it a test on your awesome Mac and let me know if it works OK? Seems to be working fine under Linux.

**Comment by sam-artuso** [comment]
I can confirm this works 14.3 (arm64 architecture).

Amazing job! 🥳

**Comment by sam-artuso** [comment]
And thank you for including me in the Thanks section of the readme!

**Comment by sam-artuso** [comment]
I suppose this issue can be closed now?

**Comment by marcopaganini** [comment]
Closed! Thanks!
