### ISSUE TITLE
Plain text (and possibly json) output with issuer always present and without header

### ISSUE THREAD

**Issue by timkgh** [marcopaganini/termotp#5]
Please provide a plain text output mode that does not have the ISSUER header line and includes the issuer on all lines. This is useful to pipe the output to `grep`. Entries that have the same issuer do not show the issuer which makes it hard to grep by issuer.

It could also be nice to provide JSON output so that it can be processed by tools such as `jq`.

**Comment by marcopaganini** [comment]
Version 0.0.9 (just pushed) removes automerge for plain output (this was the plan all along) and add json output support.

**Comment by timkgh** [comment]
Amazing! Thank you.
